### ISSUE TITLE
サイト生成

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/hacku-kosen-2022-backend#12]
# Overview 

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by kathmandu777** [comment]
@m-star18 と一緒にどのようにするかの構成を考える -> @igsr5 のレビューをもらう -> 実装

**Comment by igsr5** [comment]
https://github.com/youngeek-0410/hacku-kosen-2022/issues/26 で一括で進めているのでこっちは close
