### ISSUE TITLE
spotify music uri

### ISSUE THREAD

**Issue by kathmandu777** [youngeek-0410/hacku-kosen-2022-backend#22]
# Overview 
URIフィールドを忘れていたので追加する

# Background of the improvement 

# Requirements 

# Considerations 
- 

# Implementation policy 
- 

# Test items 
- 

# Remarks

**Comment by kathmandu777** [comment]
album, artistにdescriptionフィールドも追加されたので追従する

**Comment by m-star18** [comment]
@kathmandu777 
openapi.yamlのとこ見たんだけど
>     SpotifyMusic:
>       type: object
>       properties:
>         uri:
>           type: string
>           description: 楽曲を識別するURI
>           example: "uri:ljadjoihjgsadih"
>         name:
>           type: string
>           description: 楽曲名
>           example: ジョジョ~その血の運命~
>         external_url:
>           type: string
>           description: SpotifyページへのURL
>           example: https://spotify.com/...
>         preview_url:
>           type: string
>           description: サンプル30秒の音声データのURL
>           example: https://spotify.com/...
>         artist:
>           type: object
>           description: アーティスト情報
>           properties:
>             name:
>               type: string
>               description: アーティスト名
>               example: 富永TOMMY弘明
>             external_url:
>               type: string
>               description: SpotifyページへのURL
>               example: https://spotify.com/...
>         album:
>           type: object
>           description: アルバム情報
>           properties:
>             name:
>               type: string
>               description: アルバム名
>               example: ジョジョ~その血の運命~
>             image_url:
>               type: string
>               description: カバー画像のURL
>               example: https://spotify.com/...
これ見る感じやる必要なさそう.
