### ISSUE TITLE
Project 作成時にデフォルトの Spotify Music を設定する

### ISSUE THREAD

**Issue by igsr5** [youngeek-0410/hacku-kosen-2022-backend#55]
Project に SpotifyMusic が登録されていない、という状態を防ぎたい（ユーザ体験的にも、実装の分岐的にも）

**Comment by igsr5** [comment]
もうあと何個かほしいが、バックエンド側で以下のような配列を持っておいてProject 作成時にこの中からランダムで選んだ値を `project.spotify_music.uri` に突っ込む

```js
[
  "spotify:album:6uqewERWZ1vzfCcin1zFIp", // おもかげ
]
```

**Comment by igsr5** [comment]
## やってほしいこと

- バックエンドで事前に持っておく uri 文字列のバリデーションを増やす（5つくらいあればいい？）
- Project 作成時にこの中からランダムで選んだ値を project.spotify_music.uri

**Comment by igsr5** [comment]
とりあえずProject に SpotifyMusic が登録されていない、という状態を無くしたいのでバリエーションが1つしかなくても↓の実装を入れてほしい


> Project 作成時にこの中から事前に用意したuri値を project.spotify_music.uri に入れる

**Comment by m-star18** [comment]
やること把握した🙆‍♂️
事前に持っておきたい曲のリスト(5個くらい？)をどれにするか教えて欲しい

**Comment by igsr5** [comment]
とりあえず上のコメントにあげた1つだけで進めちゃっていいよー

**Comment by m-star18** [comment]
OK!

**Comment by m-star18** [comment]
#56
